spring:
  application:
    name: data-modeling
  datasource:
    url: jdbc:mysql://localhost:3306/db_data_modeling_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: "TaM123456789@"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type:
          json_format_mapper: jackson
